version: '3'
services:
  db:
    image: mysql
    environment:
    - MYSQL_DATABASE=hellospring
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ROOT_HOST=%
    ports:
    - 3306:3306

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
    - docker-compose.env
    ports:
    - 8081:8081
    links:
    - db
    depends_on:
    - db

